// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: product.proto

package product

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Product service

func NewProductEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Product service

type ProductService interface {
	AddProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ProductResponse, error)
	UpdateProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ProductResponse, error)
	DeleteProductById(ctx context.Context, in *RequestId, opts ...client.CallOption) (*ProductResponse, error)
	FindProductById(ctx context.Context, in *RequestId, opts ...client.CallOption) (*ProductInfo, error)
	FindProductAll(ctx context.Context, in *RequestAll, opts ...client.CallOption) (*AllProduct, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) AddProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "Product.AddProduct", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) UpdateProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "Product.UpdateProduct", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) DeleteProductById(ctx context.Context, in *RequestId, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "Product.DeleteProductById", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) FindProductById(ctx context.Context, in *RequestId, opts ...client.CallOption) (*ProductInfo, error) {
	req := c.c.NewRequest(c.name, "Product.FindProductById", in)
	out := new(ProductInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) FindProductAll(ctx context.Context, in *RequestAll, opts ...client.CallOption) (*AllProduct, error) {
	req := c.c.NewRequest(c.name, "Product.FindProductAll", in)
	out := new(AllProduct)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Product service

type ProductHandler interface {
	AddProduct(context.Context, *ProductInfo, *ProductResponse) error
	UpdateProduct(context.Context, *ProductInfo, *ProductResponse) error
	DeleteProductById(context.Context, *RequestId, *ProductResponse) error
	FindProductById(context.Context, *RequestId, *ProductInfo) error
	FindProductAll(context.Context, *RequestAll, *AllProduct) error
}

func RegisterProductHandler(s server.Server, hdlr ProductHandler, opts ...server.HandlerOption) error {
	type product interface {
		AddProduct(ctx context.Context, in *ProductInfo, out *ProductResponse) error
		UpdateProduct(ctx context.Context, in *ProductInfo, out *ProductResponse) error
		DeleteProductById(ctx context.Context, in *RequestId, out *ProductResponse) error
		FindProductById(ctx context.Context, in *RequestId, out *ProductInfo) error
		FindProductAll(ctx context.Context, in *RequestAll, out *AllProduct) error
	}
	type Product struct {
		product
	}
	h := &productHandler{hdlr}
	return s.Handle(s.NewHandler(&Product{h}, opts...))
}

type productHandler struct {
	ProductHandler
}

func (h *productHandler) AddProduct(ctx context.Context, in *ProductInfo, out *ProductResponse) error {
	return h.ProductHandler.AddProduct(ctx, in, out)
}

func (h *productHandler) UpdateProduct(ctx context.Context, in *ProductInfo, out *ProductResponse) error {
	return h.ProductHandler.UpdateProduct(ctx, in, out)
}

func (h *productHandler) DeleteProductById(ctx context.Context, in *RequestId, out *ProductResponse) error {
	return h.ProductHandler.DeleteProductById(ctx, in, out)
}

func (h *productHandler) FindProductById(ctx context.Context, in *RequestId, out *ProductInfo) error {
	return h.ProductHandler.FindProductById(ctx, in, out)
}

func (h *productHandler) FindProductAll(ctx context.Context, in *RequestAll, out *AllProduct) error {
	return h.ProductHandler.FindProductAll(ctx, in, out)
}
